# Generated by Django 4.2.7 on 2023-11-12 15:45

from django.db import migrations
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_article_author_alter_article_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=froala_editor.fields.FroalaField(),
        ),
    ]
