# Generated by Django 4.2.7 on 2023-11-13 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_article_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
